
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;


import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell-PC
 */


    //private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      //      t.start();        // TODO add your handling code here:
   // }                                        

    /**
     * @param args the command line arguments
     */
  /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
*/
        //</editor-fold>

        /* Create and display the form */
/*        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timer().setVisible(true);
            }
        });
    }
*/
public class question extends javax.swing.JFrame {
//public class timer extends javax.swing.JFrame {

    /**
     * Creates new form timer
     */
  static  int score=0;
    
static int i=0;
static int j=0;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dushyant
 */

       
            
private Timer t;
   public ActionListener al;
   long start;
     char op;
     String type;
   
   public long Stopwatch() {
        start = System.currentTimeMillis();
        return start;
    }
     public double elapsedTime(long timer) {
        long now = System.currentTimeMillis();
        return (now - timer) / 1000.0;
    }
    /**
     * Creates new form question
     */
    public question() {
        initComponents();
        al=new ActionListener(){
           public void actionPerformed(ActionEvent ae){
            if(jProgressBar1.getValue()<100)
            {jProgressBar1.setValue(jProgressBar1.getValue()+10);}
            else{t.stop();
                System.out.println("DONe");
                 jProgressBar1.setValue(0);
            jButton1.doClick();}
           }
    };
            
    t=new Timer(1000,al);        
    }        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-texture-1014963_960_720_1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(177, 160, 167));
        setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("question");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 950, 60);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(50, 280, 490, 50);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(50, 350, 490, 50);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(550, 270, 430, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesEEAOH67S.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 430, 98, 83);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Qno.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 90, 90, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 460, 180, 50);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(110, 30, 620, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(780, 30, 110, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(620, 150, 50, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("Difficulty Level");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 110, 80, 30);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(550, 330, 430, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /* 

        pack();
    }//
    </editor-fold> */            
    public int randomnum(int i){ 
        Random r = new Random();
         int Result=0;
               
                 int Low = 1;
            int High = 30;
            int m=r.nextInt(High);
             Result = r.nextInt(m);
            //return Result;
            
            /*  }
                
                
              else if(i>3||i<7){
                    int Low = 1;
            int High = 30;
             Result = r.nextInt(High) + Low;
              //         String q="select * from "+"where sno="+r+" ;";
            //  return Result;
                }
              
              else if (i>7){
                    int Low = 1;
            int High = 30;
             Result = r.nextInt(High) + Low;
            //return Result;
                 //      String q="select * from "+"where sno="+r+" ;";
                }*/
        return Result;
         
    }
    
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
           // jButton1.doClick();
            
      
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   jButton2.setVisible(true);
jButton1.setVisible(false);
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
jRadioButton5.setSelected(false);
jRadioButton4.setSelected(false);
        j=j+1;
   if(j>10){
try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/quiz","root","root");
            //Date date = new Date();
           // String timef=(String)date.toString();
            //String time1=String.valueOf(timef);
      // display time and date using toString()
        //  int timef=String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
    Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
    
    
           // String q="insert into score(user_name,score,time) values ('"+(login.n)+"',"+(score)+","+currentTimestamp+");";
            
            //JOptionPane.showMessageDialog(this,q);
             

            PreparedStatement stmt=con.prepareStatement("INSERT INTO score (user_name,category,score,time) VALUES (?, ?, ?, ?)");
            
            stmt.setString(1,login.n);
            stmt.setString(2,subject.subject);
            stmt.setInt(3, (int) score);
            stmt.setTimestamp(4,currentTimestamp);
            stmt.executeUpdate();
            
           // JOptionPane.showMessageDialog(this,"Data successfully inseted.");
             
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

     
       new quiz_end().setVisible(true);
      this.setVisible(false);
      
      i=0;
      j=0;
      
   }
   else {
       jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
jRadioButton5.setSelected(false);
jRadioButton4.setSelected(false);
        
   jRadioButton1.setText("");
   jRadioButton2.setText("");
   jRadioButton5.setText("");
   jRadioButton4.setText("");
   jLabel1.setText("");
   
   int k=randomnum(j);
  try{ Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/quiz", "root", "root");
            Statement stmt=con.createStatement();
            int n1=0;
   String q="select * from "+subject.subject +" where sno ="+k+" ;";
   //JOptionPane.showMessageDialog(this,q);
            ResultSet rs=stmt.executeQuery(q);
             String aa="";
            while(rs.next())
            {    jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
jRadioButton5.setSelected(false);
jRadioButton4.setSelected(false);
        
                jLabel1.setText(rs.getString(2));
                jLabel3.setText(String.valueOf(j));
                jRadioButton1.setText(rs.getString(5));
                jRadioButton2.setText(rs.getString(6));
                jRadioButton5.setText(rs.getString(7));
                jRadioButton4.setText(rs.getString(8));
                aa=rs.getString(4);
                op=aa.charAt(0);
                type=rs.getString(3);
                jTextField3.setText(type);
                
            }
            
               
                
                
            
           
            
            
            
            
 
            
            rs.close();
            stmt.close();
            con.close();
  }
  catch(Exception e){
      JOptionPane.showMessageDialog(this, e.getMessage());
      
  }
  t.start();
   timer1=Stopwatch();
   }   //  jButton1.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
long timer1;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
t.stop();
jProgressBar1.setValue(0);


        jButton1.setVisible(true);
jButton2.setVisible(false);
        long timer2 = Stopwatch();
        
        long time2 =(long) elapsedTime(timer1);
        
        jTextField1.setText(String.valueOf(time2)); 
        int k=0;
       char m='A';
       if(jRadioButton1.isSelected())
 {
   m='A'; 
 }
       else if(jRadioButton2.isSelected())
 {
    m='B';
 }
    else   if(jRadioButton4.isSelected())
 {
    m='C';//code
 }
    else   if(jRadioButton5.isSelected())
 {
    m='D';
 } else m='0';
       
       if(m==op){
        if(type.equals("E")) k=1;
        else if(type.equals("M")) k=2;
        else k=3;
        
        score=score+k*(10-(int)time2);
                }
// TODO add your handling code here:

    

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question().setVisible(true);
                //new timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
